/* CVS $Id: $ */
package net.interition.sparlycode.ahkbp.model; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /Users/pjworrall/Documents/Java2RDF/sparqlycode/sparqlycode-apache-http-kb/src/main/resources/HTTPO.ttl 
 * @author Auto-generated by schemagen on 08 Apr 2015 13:27 
 */
public class HTTPO {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://ontology.interition.net/apache/http/ref/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property proxied = m_model.createProperty( "http://ontology.interition.net/apache/http/ref/proxied" );
    
    public static final Property proxy = m_model.createProperty( "http://ontology.interition.net/apache/http/ref/proxy" );
    
    public static final Property proxyPass = m_model.createProperty( "http://ontology.interition.net/apache/http/ref/proxyPass" );
    
    public static final Property serverName = m_model.createProperty( "http://ontology.interition.net/apache/http/ref/serverName" );
    
    public static final Resource External = m_model.createResource( "http://ontology.interition.net/apache/http/ref/External" );
    
    public static final Resource Internal = m_model.createResource( "http://ontology.interition.net/apache/http/ref/Internal" );
    
    public static final Resource VirtualHost = m_model.createResource( "http://ontology.interition.net/apache/http/ref/VirtualHost" );
    
}
