prefix id:    <http://www.interition.net/apache/http/id/>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix web:   <http://ontology.interition.net/apache/http/ref/>


ASK WHERE {

			?v a web:VirtualHost .
			
}  

